### ISSUE TITLE
fails on extra whitespace between msgstr and text 

### ISSUE THREAD

**Issue by dfherr** [arashm/PoParser#7]
whitespace between msgstr and quotes produce parsing errors (same goes for msgctxt and msgid)

Example file:

```

# Test whitespace po
# Copyright (c) 2014 Experteer GmbH
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Version 1\n"
"POT-Creation-Date: 2016-11-09 17:12+0100\n"
"PO-Revision-Date: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"



#       excelrow: 9
#: ../../app/b_logic/a/b/xyz.rb:68
#:      ../../app/b_logic/a/e/art.rb:80
msgctxt "Signup"
msgid "Registrierung erfolgreich!"
msgstr          "Registration succesful!"
```

msgcat output:

```
# Test whitespace po
# Copyright (c) 2014 Experteer GmbH
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Version 1\n"
"POT-Creation-Date: 2016-11-09 17:12+0100\n"
"PO-Revision-Date: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#       excelrow: 9
#: ../../app/b_logic/a/b/xyz.rb:68 ../../app/b_logic/a/e/art.rb:80
msgctxt "Signup"
msgid "Registrierung erfolgreich!"
msgstr "Registration succesful!"
```

the parser:

```
po = PoParser.parse("/home/dherr/test/testpo/whitespace_test_head.po")
Parslet::ParseFailed: Extra input after last repetition at line 6 char 1.
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parslet-1.7.1/lib/parslet/cause.rb:70:in `raise'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parslet-1.7.1/lib/parslet/atoms/base.rb:49:in `parse'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/PoParser-1.0.3/lib/poparser/tokenizer.rb:30:in `parse_block'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/PoParser-1.0.3/lib/poparser/tokenizer.rb:15:in `block (2 levels) in extract_entries'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/PoParser-1.0.3/lib/poparser/tokenizer.rb:13:in `each_line'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/PoParser-1.0.3/lib/poparser/tokenizer.rb:13:in `block in extract_entries'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/PoParser-1.0.3/lib/poparser/tokenizer.rb:12:in `open'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/PoParser-1.0.3/lib/poparser/tokenizer.rb:12:in `extract_entries'
	from /home/dherr/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/PoParser-1.0.3/lib/poparser.rb:19:in `parse'
	from (irb):37
	from /home/dherr/.rbenv/versions/2.2.4/bin/irb:11:in `<main>'
```

**Comment by arashm** [comment]
Fixed on master.
